### ISSUE TITLE
Gradle-import in IntelliJ fails because of missing property ossrhUsername

### ISSUE THREAD

**Issue by fwilhe** [jimschubert/kopper#1]
When I import the project into intellij, it fails with this message:

> Error:(63, 0) Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

It should be tested if the property exists before it is used.

**Comment by jimschubert** [comment]
Thanks for reporting this. I've just added placeholders for user/pass in gradle.properties, which should resolve the import.
