### ISSUE TITLE
Weird default value behavior

### ISSUE THREAD

**Issue by SpaceBison** [jimschubert/kopper#7]
When defining a string option with default value, the default will be applied only if the option appears on the command line without explicit value parameter. Otherwise the delegate returns an empty string.

I find this counter-intuitive; I would rather expect that omitting the value in the arguments will cause the default value to be used and using a string option without value will either also return the default or throw an error ("option -x requires a parameter").

In case this is intended, it would be nice to have it configurable.

**Comment by jimschubert** [comment]
@SpaceBison thanks for reporting this. I've fixed the problem via 704d43eace3424d0c0bad15de27260bcce116adc and published 0.0.4 to Sonatype Releases. It'll probably take a day or two for that to propagate to maven central.

**Comment by SpaceBison** [comment]
@jimschubert Wow, that was quick. Thanks a lot!
